[package]
name = "xmas_letters"
type = "contract"
authors = ["Ciara Nightingale"]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v3.0.0-nightly.20251209", directory = "noir-projects/aztec-nr/aztec" }